(sdk
 (format_version 1)
 (bonsai_swiftui_version 0.1.0~dev)
 (bonsai_swiftui_source
  1c7d768c225fdc01b6531dd379c77f7d8ddf23e9
  sha256
  3340f686f71233c016db514d7588c9ca8ebee58597ba5d04ef8493b14c47433a)
 (abi_version 4)
 (ocaml_version 5.1.1)
 (dune_version_range 3.17 4.0)
 (cross_compiler ocaml-ios64-simulator 5.1.1)
 (findlib_toolchain ios)
 (architecture arm64)
 (platform iossimulator)
 (minimum_deployment_target 26.0)
 (package_universe_digest c9b9ac0079811466163a2d2a74f726d78579b281b8f8561ad2c97f0fecb04189)
 (target_components_digest eae3fcc8ca4c556602e825c0f19d0f83b652cb36fd6e846b261e9ef10ce5a21e)
 (required_frameworks Foundation Security)
 (required_system_libraries sqlite3)
 (build_recipe_revision 5)
 (packages
  (abstract_algebra v0.17.0)
  (angstrom 0.16.1)
  (asn1-combinators 0.3.2)
  (astring 0.8.5)
  (base v0.17.3)
  (base64 3.5.2)
  (base_bigstring v0.17.0)
  (base_quickcheck v0.17.0)
  (bigstringaf 0.10.0)
  (bin_prot v0.17.0-1)
  (bonsai v0.17.0)
  (bonsai_swiftui 0.1.0~dev)
  (ca-certs-nss 3.126)
  (core v0.17.2)
  (core_kernel v0.17.0)
  (cstruct 6.2.0)
  (datascript-ocaml-native dev)
  (datascript_ocaml dev)
  (digestif 1.3.1)
  (domain-local-await 1.0.1)
  (domain-name 0.5.0)
  (eio 1.2)
  (eio_posix 1.2)
  (eqaf 0.10)
  (faraday 0.8.2)
  (fieldslib v0.17.0)
  (fmt 0.11.0)
  (gel v0.17.0)
  (gluten 0.5.2)
  (gluten-eio 0.5.2)
  (gmap 0.3.0)
  (gmp-sys-ios 6.3.0)
  (hmap 0.8.1)
  (httpun 0.2.0)
  (httpun-eio 0.2.0)
  (httpun-types 0.2.0)
  (httpun-ws 0.2.0)
  (incr_dom v0.17.0)
  (incr_map v0.17.0)
  (incr_select v0.17.0)
  (incremental v0.17.0)
  (int_repr v0.17.0)
  (iomux 0.4)
  (ipaddr 5.6.2)
  (jane-street-headers v0.17.0)
  (jst-config v0.17.0)
  (kdf 1.1.0)
  (logs 0.10.0)
  (lwt-dllist 1.1.0)
  (macaddr 5.6.2)
  (melange-edn-core 0.5.0)
  (melange-edn-native 0.5.0)
  (melange-transit-core 0.1.2)
  (melange-transit-native 0.1.2)
  (mirage-crypto 2.2.0)
  (mirage-crypto-ec 2.2.0)
  (mirage-crypto-pk 2.2.0)
  (mirage-crypto-rng 2.2.0)
  (mirage-ptime 5.2.0)
  (mtime 2.1.0)
  (ocaml-ios64-simulator 5.1.1)
  (ocaml_intrinsics_kernel v0.17.2)
  (ohex 0.2.0)
  (optint 0.3.0)
  (parsexp v0.17.0)
  (persistent_sorted_set_ocaml dev)
  (ppx_assert v0.17.0)
  (ppx_bench v0.17.0)
  (ppx_compare v0.17.0)
  (ppx_deriving 6.0.3)
  (ppx_deriving_yojson 3.9.1)
  (ppx_diff v0.17.0)
  (ppx_enumerate v0.17.0)
  (ppx_expect v0.17.0)
  (ppx_hash v0.17.0)
  (ppx_here v0.17.0)
  (ppx_inline_test v0.17.0)
  (ppx_log v0.17.0)
  (ppx_module_timer v0.17.0)
  (ppx_sexp_conv v0.17.0)
  (ppx_stable_witness v0.17.0)
  (ppx_string v0.17.0)
  (ppxlib 0.35.0)
  (psq 0.2.1)
  (ptime 1.2.0)
  (rrbvec dev)
  (sexplib v0.17.0)
  (sexplib0 v0.17.0)
  (splittable_random v0.17.0)
  (sqlite3 5.4.0)
  (stdio v0.17.0)
  (stringext 1.6.0)
  (thread-table 1.0.0)
  (time_now v0.17.0)
  (tls 2.1.2)
  (tls-eio 2.1.2)
  (typerep v0.17.1)
  (uopt v0.17.0)
  (uri 4.4.0)
  (uucp 17.0.0)
  (uunf 17.0.0)
  (uutf 1.0.4)
  (variantslib v0.17.0)
  (virtual_dom v0.17.0)
  (x509 1.1.1)
  (yojson 3.0.0)
  (zarith 1.14)
 )
 (libraries
  (jst-config jst-config v0.17.0 (jst-config))
  (abstract_algebra abstract_algebra v0.17.0 (abstract_algebra))
  (angstrom angstrom 0.16.1 (angstrom))
  (asn1-combinators asn1-combinators 0.3.2 (asn1-combinators))
  (astring astring 0.8.5 (astring))
  (base base v0.17.3 (base base.base_internalhash_types base.md5 base.shadow_stdlib))
  (base.base_internalhash_types base v0.17.3 (base base.base_internalhash_types base.md5 base.shadow_stdlib))
  (base.md5 base v0.17.3 (base base.base_internalhash_types base.md5 base.shadow_stdlib))
  (base.shadow_stdlib base v0.17.3 (base base.base_internalhash_types base.md5 base.shadow_stdlib))
  (base64 base64 3.5.2 (base64))
  (base_bigstring base_bigstring v0.17.0 (base_bigstring))
  (base_quickcheck base_quickcheck v0.17.0 (base_quickcheck base_quickcheck.ppx_quickcheck.runtime))
  (base_quickcheck.ppx_quickcheck.runtime base_quickcheck v0.17.0 (base_quickcheck base_quickcheck.ppx_quickcheck.runtime))
  (bigstringaf bigstringaf 0.10.0 (bigstringaf))
  (bin_prot bin_prot v0.17.0-1 (bin_prot bin_prot.shape))
  (bin_prot.shape bin_prot v0.17.0-1 (bin_prot bin_prot.shape))
  (bonsai bonsai v0.17.0 (bonsai bonsai.driver))
  (bonsai.driver bonsai v0.17.0 (bonsai bonsai.driver))
  (ca-certs-nss ca-certs-nss 3.126 (ca-certs-nss))
  (core core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core.base_for_tests core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core.command core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core.filename_base core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core.heap_block core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core.univ_map core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core.validate core v0.17.2 (core core.base_for_tests core.command core.filename_base core.heap_block core.univ_map core.validate))
  (core_kernel.balanced_reducer core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.reversed_list core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.thread_safe_queue core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.timing_wheel core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.tuple_pool core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.weak_array core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.weak_hashtbl core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (core_kernel.weak_pointer core_kernel v0.17.0 (core_kernel.balanced_reducer core_kernel.reversed_list core_kernel.thread_safe_queue core_kernel.timing_wheel core_kernel.tuple_pool core_kernel.weak_array core_kernel.weak_hashtbl core_kernel.weak_pointer))
  (cstruct cstruct 6.2.0 (cstruct))
  (datascript-ocaml-native datascript-ocaml-native dev (datascript-ocaml-native datascript-ocaml-native.sqlite))
  (datascript-ocaml-native.sqlite datascript-ocaml-native dev (datascript-ocaml-native datascript-ocaml-native.sqlite))
  (datascript_ocaml datascript_ocaml dev (datascript_ocaml datascript_ocaml.types))
  (datascript_ocaml.types datascript_ocaml dev (datascript_ocaml datascript_ocaml.types))
  (digestif digestif 1.3.1 (digestif digestif.c))
  (digestif.c digestif 1.3.1 (digestif digestif.c))
  (domain-local-await domain-local-await 1.0.1 (domain-local-await))
  (domain-name domain-name 0.5.0 (domain-name))
  (eio eio 1.2 (eio eio.core eio.runtime_events eio.unix eio.utils))
  (eio.core eio 1.2 (eio eio.core eio.runtime_events eio.unix eio.utils))
  (eio.runtime_events eio 1.2 (eio eio.core eio.runtime_events eio.unix eio.utils))
  (eio.unix eio 1.2 (eio eio.core eio.runtime_events eio.unix eio.utils))
  (eio.utils eio 1.2 (eio eio.core eio.runtime_events eio.unix eio.utils))
  (eio_posix eio_posix 1.2 (eio_posix))
  (eqaf eqaf 0.10 (eqaf))
  (faraday faraday 0.8.2 (faraday))
  (fieldslib fieldslib v0.17.0 (fieldslib))
  (fmt fmt 0.11.0 (fmt))
  (gel gel v0.17.0 (gel))
  (gluten gluten 0.5.2 (gluten))
  (gluten-eio gluten-eio 0.5.2 (gluten-eio))
  (gmap gmap 0.3.0 (gmap))
  (hmap hmap 0.8.1 (hmap))
  (httpun httpun 0.2.0 (httpun))
  (httpun-eio httpun-eio 0.2.0 (httpun-eio))
  (httpun-types httpun-types 0.2.0 (httpun-types))
  (httpun-ws httpun-ws 0.2.0 (httpun-ws))
  (incr_dom.ui_incr incr_dom v0.17.0 (incr_dom.ui_incr incr_dom.ui_time_source))
  (incr_dom.ui_time_source incr_dom v0.17.0 (incr_dom.ui_incr incr_dom.ui_time_source))
  (incr_map incr_map v0.17.0 (incr_map))
  (incr_select incr_select v0.17.0 (incr_select))
  (incremental incremental v0.17.0 (incremental incremental.incremental_step_function))
  (incremental.incremental_step_function incremental v0.17.0 (incremental incremental.incremental_step_function))
  (int_repr int_repr v0.17.0 (int_repr))
  (iomux iomux 0.4 (iomux))
  (ipaddr ipaddr 5.6.2 (ipaddr))
  (jane-street-headers jane-street-headers v0.17.0 (jane-street-headers))
  (kdf.hkdf kdf 1.1.0 (kdf.hkdf kdf.pbkdf))
  (kdf.pbkdf kdf 1.1.0 (kdf.hkdf kdf.pbkdf))
  (logs logs 0.10.0 (logs))
  (lwt-dllist lwt-dllist 1.1.0 (lwt-dllist))
  (macaddr macaddr 5.6.2 (macaddr))
  (melange-edn-core melange-edn-core 0.5.0 (melange-edn-core))
  (melange-edn-native melange-edn-native 0.5.0 (melange-edn-native))
  (melange-transit-core melange-transit-core 0.1.2 (melange-transit-core))
  (melange-transit-native melange-transit-native 0.1.2 (melange-transit-native))
  (mirage-crypto mirage-crypto 2.2.0 (mirage-crypto))
  (mirage-crypto-ec mirage-crypto-ec 2.2.0 (mirage-crypto-ec))
  (mirage-crypto-pk mirage-crypto-pk 2.2.0 (mirage-crypto-pk))
  (mirage-crypto-rng mirage-crypto-rng 2.2.0 (mirage-crypto-rng mirage-crypto-rng.unix))
  (mirage-crypto-rng.unix mirage-crypto-rng 2.2.0 (mirage-crypto-rng mirage-crypto-rng.unix))
  (mirage-ptime mirage-ptime 5.2.0 (mirage-ptime mirage-ptime.unix))
  (mirage-ptime.unix mirage-ptime 5.2.0 (mirage-ptime mirage-ptime.unix))
  (mtime mtime 2.1.0 (mtime mtime.clock mtime.clock.os))
  (mtime.clock mtime 2.1.0 (mtime mtime.clock mtime.clock.os))
  (mtime.clock.os mtime 2.1.0 (mtime mtime.clock mtime.clock.os))
  (ocaml_intrinsics_kernel ocaml_intrinsics_kernel v0.17.2 (ocaml_intrinsics_kernel))
  (ohex ohex 0.2.0 (ohex))
  (optint optint 0.3.0 (optint))
  (parsexp parsexp v0.17.0 (parsexp))
  (persistent_sorted_set_ocaml persistent_sorted_set_ocaml dev (persistent_sorted_set_ocaml persistent_sorted_set_ocaml.native))
  (persistent_sorted_set_ocaml.native persistent_sorted_set_ocaml dev (persistent_sorted_set_ocaml persistent_sorted_set_ocaml.native))
  (ppx_assert.runtime-lib ppx_assert v0.17.0 (ppx_assert.runtime-lib))
  (ppx_bench.runtime-lib ppx_bench v0.17.0 (ppx_bench.runtime-lib))
  (ppx_compare.runtime-lib ppx_compare v0.17.0 (ppx_compare.runtime-lib))
  (ppx_deriving.runtime ppx_deriving 6.0.3 (ppx_deriving.runtime))
  (ppx_deriving_yojson.runtime ppx_deriving_yojson 3.9.1 (ppx_deriving_yojson.runtime))
  (ppx_diff.diffable ppx_diff v0.17.0 (ppx_diff.diffable ppx_diff.diffable_cinaps))
  (ppx_diff.diffable_cinaps ppx_diff v0.17.0 (ppx_diff.diffable ppx_diff.diffable_cinaps))
  (ppx_enumerate.runtime-lib ppx_enumerate v0.17.0 (ppx_enumerate.runtime-lib))
  (ppx_expect.config ppx_expect v0.17.0 (ppx_expect.config ppx_expect.config_types ppx_expect.make_corrected_file ppx_expect.runtime))
  (ppx_expect.config_types ppx_expect v0.17.0 (ppx_expect.config ppx_expect.config_types ppx_expect.make_corrected_file ppx_expect.runtime))
  (ppx_expect.make_corrected_file ppx_expect v0.17.0 (ppx_expect.config ppx_expect.config_types ppx_expect.make_corrected_file ppx_expect.runtime))
  (ppx_expect.runtime ppx_expect v0.17.0 (ppx_expect.config ppx_expect.config_types ppx_expect.make_corrected_file ppx_expect.runtime))
  (ppx_hash.runtime-lib ppx_hash v0.17.0 (ppx_hash.runtime-lib))
  (ppx_here.runtime-lib ppx_here v0.17.0 (ppx_here.runtime-lib))
  (ppx_inline_test.config ppx_inline_test v0.17.0 (ppx_inline_test.config ppx_inline_test.runtime-lib))
  (ppx_inline_test.runtime-lib ppx_inline_test v0.17.0 (ppx_inline_test.config ppx_inline_test.runtime-lib))
  (ppx_log.syntax ppx_log v0.17.0 (ppx_log.syntax ppx_log.types))
  (ppx_log.types ppx_log v0.17.0 (ppx_log.syntax ppx_log.types))
  (ppx_module_timer.runtime ppx_module_timer v0.17.0 (ppx_module_timer.runtime))
  (ppx_sexp_conv.runtime-lib ppx_sexp_conv v0.17.0 (ppx_sexp_conv.runtime-lib))
  (ppx_stable_witness.runtime ppx_stable_witness v0.17.0 (ppx_stable_witness.runtime ppx_stable_witness.stable_witness))
  (ppx_stable_witness.stable_witness ppx_stable_witness v0.17.0 (ppx_stable_witness.runtime ppx_stable_witness.stable_witness))
  (ppx_string.runtime ppx_string v0.17.0 (ppx_string.runtime))
  (ppxlib.print_diff ppxlib 0.35.0 (ppxlib.print_diff))
  (psq psq 0.2.1 (psq))
  (ptime ptime 1.2.0 (ptime ptime.clock ptime.clock.os))
  (ptime.clock ptime 1.2.0 (ptime ptime.clock ptime.clock.os))
  (ptime.clock.os ptime 1.2.0 (ptime ptime.clock ptime.clock.os))
  (rrbvec rrbvec dev (rrbvec))
  (sexplib sexplib v0.17.0 (sexplib))
  (sexplib0 sexplib0 v0.17.0 (sexplib0))
  (splittable_random splittable_random v0.17.0 (splittable_random))
  (sqlite3 sqlite3 5.4.0 (sqlite3))
  (stdio stdio v0.17.0 (stdio))
  (stringext stringext 1.6.0 (stringext))
  (thread-table thread-table 1.0.0 (thread-table))
  (time_now time_now v0.17.0 (time_now))
  (tls tls 2.1.2 (tls))
  (tls-eio tls-eio 2.1.2 (tls-eio))
  (typerep typerep v0.17.1 (typerep))
  (uopt uopt v0.17.0 (uopt))
  (uri uri 4.4.0 (uri))
  (uucp uucp 17.0.0 (uucp))
  (uunf uunf 17.0.0 (uunf))
  (uutf uutf 1.0.4 (uutf))
  (variantslib variantslib v0.17.0 (variantslib))
  (virtual_dom.ui_effect virtual_dom v0.17.0 (virtual_dom.ui_effect))
  (x509 x509 1.1.1 (x509))
  (yojson yojson 3.0.0 (yojson))
  (zarith zarith 1.14 (zarith))
  (threads ocaml-ios64-simulator 5.1.1 (threads unix str dynlink))
  (unix ocaml-ios64-simulator 5.1.1 (threads unix str dynlink))
  (str ocaml-ios64-simulator 5.1.1 (threads unix str dynlink))
  (dynlink ocaml-ios64-simulator 5.1.1 (threads unix str dynlink))
  (bonsai_swiftui bonsai_swiftui 0.1.0~dev (bonsai_swiftui bonsai_swiftui.driver bonsai_swiftui.native_backend bonsai_swiftui.protocol bonsai_swiftui.runtime bonsai_swiftui.runtime_adapter bonsai_swiftui.spec bonsai_swiftui.spec_impl bonsai_swiftui.ui))
  (bonsai_swiftui.driver bonsai_swiftui 0.1.0~dev (bonsai_swiftui bonsai_swiftui.driver bonsai_swiftui.native_backend bonsai_swiftui.protocol bonsai_swiftui.runtime bonsai_swiftui.runtime_adapter bonsai_swiftui.spec bonsai_swiftui.spec_impl bonsai_swiftui.ui))
  (bonsai_swiftui.native_backend bonsai_swiftui 0.1.0~dev (bonsai_swiftui bonsai_swiftui.driver bonsai_swiftui.native_backend bonsai_swiftui.protocol bonsai_swiftui.runtime bonsai_swiftui.runtime_adapter bonsai_swiftui.spec bonsai_swiftui.spec_impl bonsai_swiftui.ui))
  (bonsai_swiftui.protocol bonsai_swiftui 0.1.0~dev (bonsai_swiftui bonsai_swiftui.driver bonsai_swiftui.native_backend bonsai_swiftui.protocol bonsai_swiftui.runtime bonsai_swiftui.runtime_adapter bonsai_swiftui.spec bonsai_swiftui.spec_impl bonsai_swiftui.ui))
  (bonsai_swiftui.runtime bonsai_swiftui 0.1.0~dev (bonsai_swiftui bonsai_swiftui.driver bonsai_swiftui.native_backend bonsai_swiftui.protocol bonsai_swiftui.runtime bonsai_swiftui.runtime_adapter bonsai_swiftui.spec bonsai_swiftui.spec_impl bonsai_swiftui.ui))
  (bonsai_swiftui.runtime_adapter bonsai_swiftui 0.1.0~dev (bonsai_swiftui bonsai_swiftui.driver bonsai_swiftui.native_backend bonsai_swiftui.protocol bonsai_swiftui.runtime bonsai_swiftui.runtime_adapter bonsai_swiftui.spec bonsai_swiftui.spec_impl bonsai_swiftui.ui))
  (bonsai_swiftui.spec bonsai_swiftui 0.1.0~dev (bonsai_swiftui bonsai_swiftui.driver bonsai_swiftui.native_backend bonsai_swiftui.protocol bonsai_swiftui.runtime bonsai_swiftui.runtime_adapter bonsai_swiftui.spec bonsai_swiftui.spec_impl bonsai_swiftui.ui))
  (bonsai_swiftui.spec_impl bonsai_swiftui 0.1.0~dev (bonsai_swiftui bonsai_swiftui.driver bonsai_swiftui.native_backend bonsai_swiftui.protocol bonsai_swiftui.runtime bonsai_swiftui.runtime_adapter bonsai_swiftui.spec bonsai_swiftui.spec_impl bonsai_swiftui.ui))
  (bonsai_swiftui.ui bonsai_swiftui 0.1.0~dev (bonsai_swiftui bonsai_swiftui.driver bonsai_swiftui.native_backend bonsai_swiftui.protocol bonsai_swiftui.runtime bonsai_swiftui.runtime_adapter bonsai_swiftui.spec bonsai_swiftui.spec_impl bonsai_swiftui.ui))
 ))
