import SwiftUI

/// Fixed-layout, sparse overrides. Native baseline values are generated by evaluating OCaml Theme.Defaults.Values.
struct SharedUIDefaults: Equatable, Sendable {
  var metrics: [Double?] = Array(repeating: nil, count: 14)
  var colors: [UInt32?] = Array(repeating: nil, count: 9)
  var textSizes: [Double?] = Array(repeating: nil, count: 8)
  var textWeights: [Int?] = Array(repeating: nil, count: 8)
  var foreground: Int?
  var extraMetrics: [Double?] = Array(repeating: nil, count: 3)
  var symbolRendering: Int?
  var textRole: Int?
  var textForegrounds: [Int?] = Array(repeating: nil, count: 8)
  var textItalics: [Bool?] = Array(repeating: nil, count: 8)
  var surfaceMaterials: [Int?] = Array(repeating: nil, count: 7)
  var surfaceShapes: [Bool?] = Array(repeating: nil, count: 7)
  var surfaceBackgrounds: [Int?] = Array(repeating: nil, count: 7)
  var surfaceTintAlphas: [Double?] = Array(repeating: nil, count: 7)
  var surfaceOpacities: [Double?] = Array(repeating: nil, count: 7)

  static func decode(_ reader: inout WireReader) throws -> Self {
    let count = Int(try reader.integer(UInt16.self))
    var data = WireReader(try reader.data(count))
    var result = Self()
    for i in result.metrics.indices {
      if try data.flag() {
        let value = try data.finiteDouble()
        guard (i == 0 || i == 2) ? value > 0 : value >= 0 else { throw TreeError.invalidProperties }
        result.metrics[i] = value
      }
    }
    for i in result.colors.indices {
      if try data.flag() { result.colors[i] = try data.integer(UInt32.self) }
    }
    for i in result.textSizes.indices {
      result.textSizes[i] = try data.positiveOptionalDouble()
      result.textWeights[i] = try data.flag() ? data.choice(3) : nil
    }
    result.foreground = try data.flag() ? data.choice(8) : nil
    for i in result.extraMetrics.indices {
      if try data.flag() {
        let value = try data.finiteDouble()
        guard i == 0 || (0...1).contains(value) else { throw TreeError.invalidProperties }
        result.extraMetrics[i] = value
      }
    }
    result.symbolRendering = try data.flag() ? data.choice(2) : nil
    result.textRole = try data.flag() ? data.choice(7) : nil
    for i in result.textSizes.indices {
      result.textForegrounds[i] = try data.flag() ? data.choice(8) : nil
      result.textItalics[i] = try data.flag() ? data.flag() : nil
    }
    for i in result.surfaceMaterials.indices {
      result.surfaceMaterials[i] = try data.flag() ? data.choice(3) : nil
      result.surfaceShapes[i] = try data.flag() ? data.flag() : nil
      result.surfaceBackgrounds[i] = try data.flag() ? data.choice(8) : nil
      if try data.flag() {
        let value = try data.finiteDouble()
        guard (0...1).contains(value) else { throw TreeError.invalidProperties }
        result.surfaceOpacities[i] = value
      }
      if try data.flag() {
        let value = try data.finiteDouble()
        guard (0...1).contains(value) else { throw TreeError.invalidProperties }
        result.surfaceTintAlphas[i] = value
      }
    }
    guard data.remaining == 0 else { throw TreeError.invalidProperties }
    return result
  }

  func inheriting(_ parent: Self) -> Self {
    var result = self
    for i in metrics.indices { result.metrics[i] = metrics[i] ?? parent.metrics[i] }
    for i in colors.indices { result.colors[i] = colors[i] ?? parent.colors[i] }
    for i in textSizes.indices {
      result.textSizes[i] = textSizes[i] ?? parent.textSizes[i]
      result.textWeights[i] = textWeights[i] ?? parent.textWeights[i]
    }
    result.foreground = foreground ?? parent.foreground
    result.symbolRendering = symbolRendering ?? parent.symbolRendering
    result.textRole = textRole ?? parent.textRole
    for i in extraMetrics.indices {
      result.extraMetrics[i] = extraMetrics[i] ?? parent.extraMetrics[i]
    }
    for i in textSizes.indices {
      result.textForegrounds[i] = textForegrounds[i] ?? parent.textForegrounds[i]
      result.textItalics[i] = textItalics[i] ?? parent.textItalics[i]
    }
    for i in surfaceMaterials.indices {
      result.surfaceMaterials[i] = surfaceMaterials[i] ?? parent.surfaceMaterials[i]
      result.surfaceShapes[i] = surfaceShapes[i] ?? parent.surfaceShapes[i]
      result.surfaceBackgrounds[i] = surfaceBackgrounds[i] ?? parent.surfaceBackgrounds[i]
      result.surfaceOpacities[i] = surfaceOpacities[i] ?? parent.surfaceOpacities[i]
      result.surfaceTintAlphas[i] = surfaceTintAlphas[i] ?? parent.surfaceTintAlphas[i]
    }
    return result
  }

  func metric(_ index: Int) -> Double { metrics[index] ?? UIDefaultValues.metrics[index] }
  func textSize(_ role: Int) -> Double { textSizes[role] ?? UIDefaultValues.textSizes[role] }
  func textWeight(_ role: Int) -> Int { textWeights[role] ?? UIDefaultValues.textWeights[role] }

  func extraMetric(_ index: Int) -> Double {
    extraMetrics[index] ?? UIDefaultValues.extraMetrics[index]
  }
  func defaultForeground() -> Int { foreground ?? UIDefaultValues.foreground }
  func defaultTextRole() -> Int { textRole ?? UIDefaultValues.textRole }
  func defaultSymbolRendering() -> Int { symbolRendering ?? UIDefaultValues.symbolRendering }
  func textForeground(_ role: Int) -> Int? {
    let value = textForegrounds[role] ?? UIDefaultValues.textForegrounds[role]
    return value < 0 ? nil : value
  }
  func textItalic(_ role: Int) -> Bool {
    textItalics[role] ?? (UIDefaultValues.textItalics[role] == 1)
  }
  func surfaceMaterial(_ role: Int) -> Int {
    surfaceMaterials[role] ?? UIDefaultValues.surfaceMaterials[role]
  }
  func surfaceCapsule(_ role: Int) -> Bool {
    surfaceShapes[role] ?? (UIDefaultValues.surfaceShapes[role] == 1)
  }
  func surfaceBackground(_ role: Int) -> Int {
    surfaceBackgrounds[role] ?? UIDefaultValues.surfaceBackgrounds[role]
  }
  func surfaceTintAlpha(_ role: Int) -> Double? {
    let value = surfaceTintAlphas[role] ?? UIDefaultValues.surfaceTintAlphas[role]
    return value < 0 ? nil : value
  }
  func surfaceOpacity(_ role: Int) -> Double {
    surfaceOpacities[role] ?? UIDefaultValues.surfaceOpacities[role]
  }

  func color(_ role: Int) -> Color {
    if let argb = colors[role] { return Color(argb: argb) }
    #if os(macOS)
      return Color(nsColor: nativeColor(role))
    #else
      return Color(uiColor: nativeColor(role))
    #endif
  }

  #if os(macOS)
    private func nativeColor(_ role: Int) -> NSColor {
      switch role {
      case 0: .labelColor
      case 1: .secondaryLabelColor
      case 2: .windowBackgroundColor
      case 3: .controlBackgroundColor
      case 4, 5: .quaternaryLabelColor
      case 6: .separatorColor
      case 7: .shadowColor.withAlphaComponent(extraMetric(1))
      default: .windowBackgroundColor.withAlphaComponent(extraMetric(2))
      }
    }
  #else
    private func nativeColor(_ role: Int) -> UIColor {
      switch role {
      case 0: .label
      case 1: .secondaryLabel
      case 2: .systemBackground
      case 3: .secondarySystemBackground
      case 4: .tertiarySystemBackground
      case 5: .tertiarySystemFill
      case 6: .separator
      case 7: .black.withAlphaComponent(extraMetric(1))
      default: .systemBackground.withAlphaComponent(extraMetric(2))
      }
    }
  #endif

  #if os(macOS)
    @MainActor func bodyFont(family: String?, legibility: LegibilityWeight?) -> NSFont {
      let weight: NSFont.Weight = [.regular, .medium, .semibold, .bold][
        legibility == .bold ? 3 : textWeight(0)]
      let base =
        family.flatMap { NSFont(name: $0, size: textSize(0)) }
        ?? NSFont.systemFont(ofSize: textSize(0), weight: weight)
      let descriptor = base.fontDescriptor.addingAttributes([
        .traits: [NSFontDescriptor.TraitKey.weight: weight.rawValue]
      ])
      return NSFont(descriptor: descriptor, size: textSize(0)) ?? base
    }
  #else
    @MainActor func bodyFont(family: String?, legibility: LegibilityWeight?) -> UIFont {
      let weight: UIFont.Weight = [.regular, .medium, .semibold, .bold][
        legibility == .bold ? 3 : textWeight(0)]
      let base =
        family.flatMap { UIFont(name: $0, size: textSize(0)) }
        ?? UIFont.systemFont(ofSize: textSize(0), weight: weight)
      let descriptor = base.fontDescriptor.addingAttributes([
        .traits: [UIFontDescriptor.TraitKey.weight: weight.rawValue]
      ])
      return UIFontMetrics(forTextStyle: .body).scaledFont(
        for: UIFont(descriptor: descriptor, size: textSize(0)))
    }
  #endif

  /// Resolve only paint colors; text and controls keep SwiftUI's semantic colors.
  func argb(_ role: Int, scheme: ColorScheme, contrast: ColorSchemeContrast) -> UInt32 {
    if let argb = colors[role] { return argb }
    #if os(macOS)
      let name: NSAppearance.Name =
        contrast == .increased
        ? (scheme == .dark ? .accessibilityHighContrastDarkAqua : .accessibilityHighContrastAqua)
        : (scheme == .dark ? .darkAqua : .aqua)
      var resolved = NSColor.clear
      NSAppearance(named: name)!.performAsCurrentDrawingAppearance {
        resolved = nativeColor(role).usingColorSpace(.sRGB)!
      }
      let components = [
        resolved.alphaComponent, resolved.redComponent, resolved.greenComponent,
        resolved.blueComponent,
      ]
    #else
      let traits = UITraitCollection(traitsFrom: [
        UITraitCollection(userInterfaceStyle: scheme == .dark ? .dark : .light),
        UITraitCollection(accessibilityContrast: contrast == .increased ? .high : .normal),
      ])
      let resolved = nativeColor(role).resolvedColor(with: traits)
      var r: CGFloat = 0
      var g: CGFloat = 0
      var b: CGFloat = 0
      var a: CGFloat = 0
      resolved.getRed(&r, green: &g, blue: &b, alpha: &a)
      let components = [a, r, g, b]
    #endif
    return components.reduce(UInt32(0)) {
      ($0 << 8) | UInt32(max(0, min(255, ($1 * 255).rounded())))
    }
  }
}

private struct SharedUIDefaultsKey: EnvironmentKey {
  static let defaultValue = SharedUIDefaults()
}
private struct BonsaiRowSpacingKey: EnvironmentKey {
  static let defaultValue: Double? = nil
}
private struct BonsaiTintKey: EnvironmentKey {
  static let defaultValue: Color? = nil
}
extension EnvironmentValues {
  var bonsaiRowSpacing: Double? {
    get { self[BonsaiRowSpacingKey.self] }
    set { self[BonsaiRowSpacingKey.self] = newValue }
  }
  var bonsaiDefaults: SharedUIDefaults {
    get { self[SharedUIDefaultsKey.self] }
    set { self[SharedUIDefaultsKey.self] = newValue }
  }
  var bonsaiTint: Color? {
    get { self[BonsaiTintKey.self] }
    set { self[BonsaiTintKey.self] = newValue }
  }
}

/// The minimum participates in layout and in the label's hit shape, so neighbors never overlap.
struct NativeInteractiveBounds: ViewModifier {
  var icon = false
  var enabled = true
  @Environment(\.controlSize) private var controlSize
  @Environment(\.bonsaiDefaults) private var defaults
  func body(content: Content) -> some View {
    #if os(iOS)
      let minimum: CGFloat? =
        !enabled || controlSize == .mini || controlSize == .small
        ? nil : CGFloat(defaults.metric(2))
      content.frame(minWidth: icon ? minimum : nil, minHeight: minimum)
        .contentShape(Rectangle())
    #else
      content
    #endif
  }
}
