((protocol
  (name bonsai_swiftui)
  (major 9)
  (minor 0)
  (endianness little)
  (header_bytes 48)
  (max_frame_bytes 16777216)
  (max_string_bytes 1048576)
  (max_application_payload_bytes 1048576)
  (max_operations 1000000)
  (max_nodes 1000000))

 (frame_kinds
  ((handshake 1)
   (full_snapshot 2)
   (incremental_frame 3)
   (event_batch 4)
   (runtime_error 5)))

 (operations
  ((begin_frame 1)
   (create_node 2)
   (update_props 3)
   (update_event_bindings 4)
   (set_children 5)
   (set_root 6)
   (drop_node 7)
   (host_request 8)
   (runtime_notification 9)
   (end_frame 10)
   (application_request 11)
   (set_application_theme 12)))

 (node_kinds
  ((empty 1)
   (text 2)
   (rich_text 3)
   (symbol 4)
   (image 5)
   (text_editor 6)
   (text_field 47)
   (secure_field 49)
   (collection_catalog 7)
   (collection_window 8)
   (scroll 9)
   (progress 10)
   (ignores_safe_area 11)
   (safe_area_padding 12)
   (navigation_stack 13)
   (navigation_destination 14)
   (navigation_split 15)
   (flow 56)
   (label 57)
   (badge 58)
   (date_picker 59)
   (time_picker 60)
   (menu 61)
   (removal 78)
   (refresh 77)
   (native_list 80)
   (list_section 81)
   (list_row 82)
   (scroll_targets 62)
   (help 63)
   (popover 72)
   (sheet 73)
   (toolbar 74)
   (scroll_sections 75)
   (scroll_section 76)
   (row 16)
   (column 17)
   (weighted_row 18)
   (stack 19)
   (weighted_column 20)
   (padding 21)
   (frame 22)
   (spacer 23)
   (layout_priority 24)
   (offset 25)
   (background 26)
   (clip 27)
   (opacity 28)
   (projection_effect 29)
   (tabs 31)
   (tab 40)
   (morphing_surface 41)
   (swipe_actions 42)
   (swipe_action 43)
   (toggle 44)
   (gesture 48)
   (focus_scope 51)
   (hover_region 52)
   (keyboard_listener 53)
   (button 54)
   (control_size 55)
   (semantics 64)
   (overlay 65)
   (theme 69)
   (animated_opacity 71)
   (divider 105)
   (group_box 106)
   (reserved_node_kind_107 107)
   (picker 116)
   (slider 45)
   (range_slider 46)
   (native_widget 128)

   (table 79)
   (disclosure_group 133)
   ))

 (common_props
  ((test_id 1 optional_string)
   (semantics 2 optional_semantics)))

 (kind_props
  ((native_list ())
   (list_section ((has_header 1 bool) (has_footer 2 bool) (separator 3 enum_u8)))
   (list_row ((separator 1 enum_u8)))
   (scroll_sections ((vertical 1 bool) (pin_headers 2 bool) (pin_footers 3 bool) (spacing 4 f64) (shows_indicators 5 bool) (initial_anchor 6 enum_u8)))
   (scroll_section ((has_header 1 bool) (has_footer 2 bool) (hero_height 3 optional_f64) (stretch 4 bool)))
   (toolbar ((placements 1 toolbar_placements)))
   (sheet ((presented 1 bool) (fullscreen 2 bool) (detents 3 u8) (initial 4 enum_u8) (interactive 5 bool) (indicator 6 bool) (sizing 7 enum_u8) (fraction 8 f64)))
   (popover ((presented 1 bool) (edge 2 enum_u8)))
   (help ((message 1 string)))
   (toggle ((value 1 bool) (enabled 2 bool) (style 3 enum_u8)))
   (swipe_actions ((enabled 1 bool) (allows_full_swipe 2 bool)))
   (swipe_action ((title 1 string) (side 2 enum_u8) (enabled 3 bool) (role 4 enum_u8) (background 5 u32) (symbol 6 optional_string)))
   (morphing_surface ((expanded 1 bool) (expand_duration_ms 2 u32) (collapse_duration_ms 3 u32)))
   (tabs ((selection 1 string)))
   (tab ((page_key 1 string) (title 2 string) (symbol 3 string) (badge 4 optional_string) (accessibility_label 5 optional_string)))
   (navigation_split ((visibility 1 u8) (compact_column 2 u8) (selection_key 3 optional_string) (sidebar_title 4 string) (content_title 5 optional_string) (detail_title 6 string)))
   (navigation_stack ((title 1 string)))
   (navigation_destination ((page_key 1 string) (title 2 string) (can_pop 3 bool)))
   (text
    ((value 1 string)
     (text_style 2 optional_text_style)
     (text_align 3 text_align)
     (line_limit 4 optional_u32)
     (truncation 5 text_truncation)))
   (rich_text
    ((spans 1 text_span_list)))
   (symbol
    ((name 1 string)
     (size 2 optional_f64)
     (color 3 optional_argb32)
     (rendering 4 symbol_rendering)))
   (scroll ((vertical 1 bool) (shows_indicators 2 bool) (fill_viewport 3 bool) (initial_anchor 4 enum_u8)))
   (collection_catalog
    ((keys 1 string_list) (default_extent 2 f64) (overrides 3 collection_extents) (overscan 4 u32)
     (expand_duration_ms 5 u32) (collapse_duration_ms 6 u32) (vertical 7 bool) (initial_anchor 8 enum_u8) (initial_key 9 optional_string) (measurement_revision 10 optional_i64)))
   (collection_window
    ((first_index 1 u32) (keys 2 string_list)))
   (text_field
    ((session_id 1 u64) (document_revision 2 u64) (accepted_local_revision 3 u64)
     (update_mode 4 text_update_mode) (value 5 text_editing_value) (enabled 6 bool)
     (read_only 7 bool) (submit_on_return 8 bool) (max_utf8_bytes 9 optional_u32)
     (label 10 string) (prompt 11 string) (keyboard 12 enum_u8) (submit_label 13 enum_u8) (autofocus 14 bool) (appearance 15 enum_u8)))
   (secure_field
    ((session_id 1 u64) (document_revision 2 u64) (accepted_local_revision 3 u64)
     (update_mode 4 text_update_mode) (value 5 text_editing_value) (enabled 6 bool)
     (read_only 7 bool) (submit_on_return 8 bool) (max_utf8_bytes 9 optional_u32)
     (label 10 string) (prompt 11 string) (keyboard 12 enum_u8) (submit_label 13 enum_u8) (autofocus 14 bool) (appearance 15 enum_u8)))
   (text_editor
    ((session_id 1 u64) (document_revision 2 u64) (accepted_local_revision 3 u64)
     (update_mode 4 text_update_mode) (value 5 text_editing_value) (enabled 6 bool)
     (read_only 7 bool) (submit_on_return 8 bool) (max_utf8_bytes 9 optional_u32)
     (autofocus 10 bool)))
   (image
    ((source 1 image_source)
     (sizing 2 image_sizing)
     (scale 3 f64)))
   (flow
    ((spacing 1 f64) (line_spacing 2 f64) (alignment 3 horizontal_alignment)))
   (row
    ((spacing 1 optional_f64)
     (alignment 2 vertical_alignment)))
   (column
    ((spacing 1 optional_f64)
     (alignment 2 horizontal_alignment)))
   (weighted_row
    ((spacing 1 optional_f64)
     (alignment 2 vertical_alignment)
     (items 3 weighted_items)))
   (weighted_column
    ((spacing 1 optional_f64)
     (alignment 2 horizontal_alignment)
     (items 3 weighted_items)))
   (stack
    ((alignment 1 alignment)))
   (layout_priority
    ((priority 1 f64)))
   (offset
    ((x 1 f64)
     (y 2 f64)))
   (padding
    ((insets 1 edge_insets)))
   (spacer
    ((min_length 1 optional_f64)))
   (frame
    ((width 1 optional_f64)
     (height 2 optional_f64)
     (min_width 3 optional_f64)
     (ideal_width 4 optional_f64)
     (max_width 5 optional_frame_limit)
     (min_height 6 optional_f64)
     (ideal_height 7 optional_f64)
     (max_height 8 optional_frame_limit)
     (alignment 9 alignment)))
   (background
    ((color 1 argb32)
     (corner_radius 2 f64)))
   (clip
    ((corner_radius 1 f64)
     (antialiased 2 bool)))
   (opacity
    ((opacity 1 f64)))
   (animated_opacity
    ((opacity 1 f64)
     (animation_id 2 u64)
     (duration_ms 3 u32)
     (curve 4 animation_curve)))
   (projection_effect
    ((matrix3 1 matrix3)))
   (focus_scope
    ((autofocus 1 bool)))
   (hover_region
    ((blocks_behind 1 bool)))
   (keyboard_listener
    ((autofocus 1 bool)
     (key_policy 2 key_policy)))
   (semantics
    ((label 1 optional_string)
     (hint 2 optional_string)
     (value 3 optional_string)
     (role 4 semantics_role)
     (selected 5 optional_bool)
     (children 6 u8)
     (hidden 7 bool)
     (live_region 8 bool)
     (heading_level 9 optional_u8)
     (sort_priority 10 optional_f64)
     (identifier 11 optional_string)
     (actions 12 semantics_actions)))
   (theme
    ((data 1 swiftui_environment)))
   (removal ((request_token 1 i64) (request_state 2 u8) (vertical 3 bool)
     (collapse_vertical 4 bool) (title 5 string) (duration_ms 6 u32)))
   (refresh ((request_token 1 i64) (request_state 2 u8) (show_token 3 optional_i64)))
   (scroll_targets ((vertical 1 bool) (ids 2 i64_list) (position 3 optional_i64)
     (fraction 4 f64) (spacing 5 f64) (alignment 6 u8) (snapping 7 bool)
     (enabled 8 bool) (shows_indicators 9 bool)))
   (menu ((items 1 menu_items) (enabled 2 bool)))
   (picker
    ((selected_id 1 optional_i64)
     (options 2 picker_options) (label 3 string) (style 4 u8) (enabled 5 bool)))
   (slider ((value 1 f64) (min 2 f64) (max 3 f64) (step 4 optional_f64) (enabled 5 bool) (vertical 6 bool) (has_on_change 7 bool) (label 8 string)))
   (range_slider ((start 1 f64) (end_value 2 f64) (min 3 f64) (max 4 f64) (step 5 optional_f64) (enabled 6 bool) (vertical 7 bool) (has_on_change 8 bool) (label_start 9 string) (label_end 10 string)))
   (divider ())
   (label ())
   (date_picker ((selected 1 civil_date) (first 2 civil_date) (last 3 civil_date)
     (label 4 string) (enabled 5 bool)))
   (time_picker ((value 1 civil_time) (format 2 u8) (label 3 string) (enabled 4 bool)))
   (badge ((count 1 optional_u64) (alignment 2 u8) (visible 3 bool)))
   (group_box
    ((has_label 1 bool)))
   (progress
    ((value 1 optional_f64)
     (style 2 enum_u8)))

   (table
    ((columns 1 table_columns)
     (rows 2 table_rows)
     (sort_column_id 3 optional_i64)
     (sort_ascending 4 bool)
     (selected_row_ids 5 i64_list)
     (has_on_sort 6 bool)
     (has_on_row_selected 7 bool)))
   (disclosure_group
    ((expanded 1 bool) (enabled 2 bool)))

   (overlay
    ((alignment 1 alignment)))
   (ignores_safe_area
    ((regions 1 u8)
     (edges 2 u8)))
   (safe_area_padding
    ((insets 1 edge_insets)))
   (control_size
    ((size 1 u8)))
   (button
    ((enabled 1 bool)
     (role 2 u8)
     (style 3 u8)
     (autofocus 4 bool)))
   (native_widget
    ((kind_id 1 u32)
     (version 2 u16)
     (capabilities 3 u64)
     (payload 4 bytes)))))

 (event_tags
  ((press 1 unit)
   (long_press 2 unit)
   (tap 3 tap)
   (double_tap 4 tap)
   (pointer_enter 5 pointer)
   (pointer_leave 6 pointer)
   (pointer_down 7 pointer)
   (pointer_up 8 pointer)
   (key 9 key)
   (focus_changed 10 bool)
   (text_edit 11 text_edit)
   (text_submit 12 string)
   (scroll_notification 13 scroll)
   (visible_range_changed 14 visible_range)
   (animation_completed 15 u64)
   (layout_observed 17 layout)
   (value_changed 18 bool)
   (host_response 19 host_response)
   (environment_changed 20 environment)
   (native_event 21 native_event)
   (semantics_action 22 u64)
   (resync_requested 23 unit)
   (text_limit_reached 24 unit)
   (application_response 25 application_response)
   (application_request_error 26 application_request_error)
   (application_event 27 application_event)
   (navigation_destination_selected 28 i64)
   (radio_selected 29 i64)
   (picker_selected 53 i64)
   (menu_action 54 i64)
   (scroll_position_changed 55 i64)
   (refresh_request 56 i64)
   (removal_requested 57 i64_pair)
   (removal_completed 58 i64)
   (slider_changed 30 f64)
   (slider_change_end 31 f64)
   (range_slider_changed 32 f64_range)
   (range_slider_change_end 33 f64_range)
   (table_sort_requested 37 i64_bool)
   (table_row_selected 38 i64_bool)
   (civil_date_changed 46 civil_date)
   (civil_time_changed 47 civil_time)


   (navigation_path_changed 50 string_list)
   (navigation_split_changed 51 navigation_split_state)
   (tab_selected 52 string)))

 (host_requests
  ((clipboard_read 1 unit string_result)
   (clipboard_write 2 string unit_result)
   (open_url 3 uri unit_result)
   (pick_files 4 file_picker_options file_list_result)
   (save_file 5 save_file_options optional_file_result)
   (request_focus 6 node_id unit_result)
   (clear_focus 7 unit unit_result)
   (scroll_to 8 scroll_to unit_result)
   (set_window_title 9 string unit_result)
   (set_window_size 10 size unit_result)
   (show_native_menu 11 native_menu menu_result)
   (haptic_feedback 12 haptic_kind unit_result)
   (platform_information 13 unit platform_information_result)
   (measure_layout 14 node_id layout_result)
   (show_notice 15 notice_options notice_close_reason_result)
   (pick_date 16 civil_date_picker_options optional_civil_date_result)
   (pick_date_range 17 civil_date_range_picker_options optional_civil_date_range_result)
   (pick_time 18 civil_time_picker_options optional_civil_time_result)))

 (runtime_errors
  ((protocol_error 1)
   (revision_mismatch 2)
   (duplicate_key 3)
   (unsupported_node_kind 4)
   (invalid_prop 5)
   (handler_missing 6)
   (stale_event 7)
   (host_effect_failure 8)
   (ocaml_exception 9)
   (swiftui_renderer_exception 10)
   (lifecycle_exception 11)
   (native_library_loading_error 12))))
